platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: "0.11.10"

inputs:
  - name: source

outputs:
  - name: secret-source
  - name: terraform-out

run:
  path: source/examples/test/tasks/apply/task.sh