name: workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with: { go-version: 1.14 }

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with: { terraform_version: 1.1.3 }

    - name: Install Taskfile
      run: curl -sL https://taskfile.dev/install.sh | sh

    - name: Run tests
      run: ./bin/task test
